name: 'Get GitHub Pull Request Reviews'
description: 'Dumps to a JSON file, all the reviews associated with a specified pull request from the GitHub API.'
author: 'Liam Pillay'
inputs:
  PULL_REQUEST_ID:
    description: 'The ID of the pull request to get the reviews of'
    required: true
  GITHUB_REPOSITORY:
    description: 'The name of the GitHub repository the pull request is on. Must be in the format `owner/repo`'
    required: true
  GITHUB_TOKEN:
    description: 'A GitHub access token that has permission to read the target pull request.'
    required: true
  FILE_NAME_OVERRIDE:
    description: 'The name of the file to write the reviews to. Please ensure you add the file extension `.json`! If not provided, the file will be named `reviews.json`'
    required: false

outputs:
  reviews_file_path:
    description: 'The path to the newly created json file containing all the reviews of the specified pull request'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'book-open'
  color: 'purple'
